[workspace]
members = [
	"strategy_pattern",
	"observer_pattern",
	"decorator_pattern",
]
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
