[package]
name = "singleton_pattern"
version = "0.1.0"
edition = "2021"

[lib]
test = false
doctest = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
